version: '3'

services:
  app:
    container_name: cryptofs-node
    command: npm start
    restart: always
    build: .
    volumes:
      - ./:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - app-tier
  mongo:
    container_name: mongo-cryptofs
    image: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
    networks:
      - app-tier
volumes:
  mongo_data:
networks:
  app-tier:
    driver: bridge
